name: NET Desktop

on:
  push:
    tags: "*"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        targetPlatform: [x64]

    runs-on: windows-latest
    env:
      Scripts_Path: TinyInstaller\Scripts
      Solution_Path: TinyInstaller\TinyInstaller.sln
      Release_Zip: TinyInstaller\TinyInstaller\bin\Release\net6.0-windows7.0\win-x64\TinyInstaller.zip

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 6.x.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@master
      
    - name: Restore dependencies
      run: dotnet restore "$env:Solution_Path"
      
    - name: Build release
      run: dotnet publish "$env:Solution_Path" -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:AssemblyVersion=${{ github.ref_name }} -p:Version=${{ github.ref_name }}

    - name: Create config file
      run: ."$env:Scripts_Path\Create-ConfigFile.ps1"
      
    - name: Copy packages to repo
      run: ."$env:Scripts_Path\Copy-RepoPackages.ps1"
      
    - name: Create zip arhive
      run: ."$env:Scripts_Path\Compress-PublishFolder.ps1"

    - name: Publish release assets
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: TinyInstaller.zip
        tag: ${{ github.ref }}
