name: Build release

on:
  push:
    branches: [ main ]
    tags: "*"

jobs:
  build:
    runs-on: windows-2016
    env:
      Script_Path: TinyInstaller\Scripts

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish -c Release -p:PublishProfile=PublishProfile -p:AssemblyVersion=${{ github.ref }} -p:Version=${{ github.ref }}
      
    - name: Create config file
      run: . "$env:Script_Path\Create-ConfigFile.ps1"
      
    - name: Copy packages to repo
      run: . "$env:Script_Path\Copy-RepoPackages.ps1"
      
    - name: Create zip arhive
      run: . "$env:Script_Path\Compress-PublishFolder.ps1"
      
    - name: Release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: TinyInstaller.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
